import { Getappcard } from "@/components/Molecules/Getappcard";
import Sidebar from "@/components/Molecules/Sidebar";
import { menuList } from "@/libs/constants";
import { Suspense } from "react";

export const metadata = {
  title: "Ngbuka Web",
  description: "Generated by Ngbuka",
};

export default function ProfilePageLayout({ children }) {     
  return (
    <>
      <div className="flex gap-3 lg:px-24 px-5 pb-10 mt-5 ">
        <div className="grid gap-10 h-fit">
        <div><Sidebar menulist={ menuList }/></div>     
        <Getappcard />
        </div>
        <Suspense fallback={'loading...'}>
        <div className="flex-1">{children}</div>
        </Suspense>
      </div>
    </>
  );
}
