import SessionWrapper from "@/components/Molecules/SessionWrapper";
import "../styles/globals.css";

export const metadata = {
  title: "Ngbuka web",
  description: "Generated by Ngbuka",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <div className="">{children}</div>
        </body>
      </html>
    </SessionWrapper>
  );
}
