// import { Inter } from "next/font/google";
import Link from "next/link";
import LandingNavbar from "@/components/Landing/LandingNavbar";
import LandingFooter from "@/components/Landing/LandingFooter";
import { CartProvider } from "@/context/CartContext";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LandinPageLayout({ children }) {
  return (
    <>
      <CartProvider>
        <LandingNavbar />
        <div className="bg-[#FFFBF5] pt-24">{children}</div>
        <LandingFooter />
      </CartProvider>
    </>
  );
}
